<a href="https://colab.research.google.com/github/Elsaamelia55/Elsa_Risti_Zalfa_EDA/blob/main/P03_Praktikum_Pertemuan3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Praktikum Pertemuan 3 — Menyiapkan Data Proyek agar Layak dan Aman Dianalisis

**Mata Kuliah:** Exploratory Data Analysis (KMTI21133) — Pertemuan 3  
**Fase PjBL:** Perencanaan  
**Sub-CPMK3:** Mahasiswa mampu merumuskan pertanyaan analisis dari masalah nyata serta memperoleh data
sesuai lisensi sumbernya, serta mengidentifikasi dan menangani data pribadi yang terkandung di dalamnya (C4, A3).

**Cara kerja.** Sel bertanda `# TODO` Anda kerjakan sendiri; setiap TODO disertai *expected output* agar Anda bisa memeriksa jawaban sendiri. Sel Markdown bertanda **Jawaban Anda** diisi dengan tulisan, bukan kode.

**Bagian A–F** dikerjakan di kelas dengan dataset latihan. **Bagian G** dikerjakan bersama tim di luar kelas dengan dataset proyek Anda sendiri, dan hasilnya menjadi isi **M1 (bobot 5%)** yang dikumpulkan sesuai tenggat di LMS.

## Bagian 0 — Persiapan

Dataset latihan: **`peserta_pelatihan_umkm_2025.csv`** — 620 baris, 28 kolom.
Data pendaftaran dan hasil pelatihan UMKM binaan kampus.

> **Catatan penting:** seluruh isi dataset ini **sintetis** dan dibuat untuk latihan. Tidak ada orang nyata di dalamnya.
> Nomor NIK, nomor telepon, dan surel sengaja dibuat dengan pola yang tidak valid. Perlakukan tetap seolah-olah data nyata,
> karena itulah kebiasaan yang sedang kita latih.

In [90]:
import pandas as pd
import numpy as np
import hashlib, os

pd.set_option('display.max_columns', 40)
pd.set_option('display.width', 140)
print('pandas', pd.__version__)

pandas 2.2.3

In [91]:
FILE = 'peserta_pelatihan_umkm_2025.csv'

if not os.path.exists(FILE):
    try:
        from google.colab import files
        files.upload()          # pilih peserta_pelatihan_umkm_2025.csv
    except ImportError:
        raise FileNotFoundError('Letakkan CSV di folder yang sama dengan notebook ini.')

df = pd.read_csv(FILE)
print(df.shape)
df.head(3)

(620, 28)

,id_peserta,nama_lengkap,nik_dummy,no_hp,email,alamat_jalan,kelurahan,kecamatan,kota,tanggal_lahir,jenis_kelamin,pendidikan_terakhir,status_disabilitas,jumlah_anak,penghasilan_pribadi_bulanan,nama_usaha,kategori_usaha,produk_utama,lama_usaha_tahun,jumlah_karyawan,omzet_usaha_bulanan,pernah_ikut_pelatihan,kanal_pendaftaran,tanggal_daftar,kehadiran_persen,skor_prates,skor_pascates,tingkat_kepuasan
0,PLT-2025-1309,Ratna Hidayat,99991405899249,8.000426e+10,ratna.hidayat@contoh.example,Jl. Cempaka No. 106 RT 02/RW 10,Sukatani,Tapos,Depok,1989-05-14,P,SMP,Tidak,3,500000,CV Mandiri Jaya,Kuliner,Roti dan kue,12.8,4,2950000,Tidak,Datang langsung,2025-04-04,75,52,67.0,5.0
1,PLT-2025-1512,Bunga Santoso,99992410874363,8.000347e+10,bunga.santoso@contoh.example,Jl. Bougenville No. 80 RT 10/RW 02,Mampang,Pancoran Mas,Depok,1987-10-24,P,D3,Tidak,1,950000,Dapur Cahaya Abadi,Jasa Digital,Servis gawai,6.5,3,7750000,Tidak,Formulir daring,2025-02-02,70,59,75.0,4.9
2,PLT-2025-1360,Endah Ramadhan,99991107987303,8.000266e+10,endah.ramadhan@contoh.example,Jl. Anggrek No. 138 RT 07/RW 08,Limo,Limo,Depok,1998-07-11,P,D3,Tidak,2,1500000,Griya Harum Makmur,Kuliner,Katering rumahan,2.5,0,7550000,Tidak,WhatsApp,2025-03-26,90,51,61.0,4.9

---
## Bagian A — Merumuskan pertanyaan analisis

Sebuah pertanyaan analisis dianggap layak bila lolos **tiga uji**:

1. **Uji kolom** — kolom mana yang akan menjawabnya?
2. **Uji bentuk jawaban** — jawabannya berupa angka, peringkat, perbandingan, atau sebaran?
3. **Uji tindak lanjut** — kalau terjawab, apa yang bisa diputuskan?

In [92]:
# TODO A1 — kenali kolom yang tersedia sebelum menulis pertanyaan
# a. Cetak daftar nama kolom beserta tipe datanya
print(df.dtypes)
# b. Cetak jumlah baris dan kolom
df.shape
# Expected: 620 baris x 28 kolom

id_peserta                      object
nama_lengkap                    object
nik_dummy                        int64
no_hp                          float64
email                           object
alamat_jalan                    object
kelurahan                       object
kecamatan                       object
kota                            object
tanggal_lahir                   object
jenis_kelamin                   object
pendidikan_terakhir             object
status_disabilitas              object
jumlah_anak                      int64
penghasilan_pribadi_bulanan      int64
nama_usaha                      object
kategori_usaha                  object
produk_utama                    object
lama_usaha_tahun               float64
jumlah_karyawan                  int64
omzet_usaha_bulanan              int64
pernah_ikut_pelatihan           object
kanal_pendaftaran               object
tanggal_daftar                  object
kehadiran_persen                 int64
skor_prates                      int64
skor_pascates                  float64
tingkat_kepuasan               float64
dtype: object

(620, 28)

### TODO A2 — perbaiki tiga pertanyaan berikut

Tulis versi perbaikannya di sel di bawah, beserta kolom yang akan dipakai.

| No | Draf pertanyaan | Masalahnya |
|---|---|---|
| 1 | Bagaimana kondisi peserta pelatihan? | Terlalu kabur |
| 2 | Apakah peserta yang lebih kaya lebih sukses? | "Kaya" dan "sukses" belum didefinisikan sebagai kolom |
| 3 | Apakah pelatihan menaikkan omzet peserta? | Uji kolom gagal — cek sendiri mengapa |

**Jawaban Anda:**

1. Perbaikan: _Bagaimana tingkat kepuasan peserta terhadap pelatihan?_ — Kolom: _tingkat kepuasan_
2. Perbaikan: _Apakah peserta dengan penghasilan pribadi bulanan lebih tinggi memiliki omzet usaha bulanan yang lebih tinggi?_ — Kolom: _penghasilan pribadi bulanan dan omzet usaha bulanan_
3. Mengapa uji kolom gagal: _Dataset tidak memiliki kolom sebelum dan sesudah pelatihan, sehingga tidak ada data yang bisa diuji_

In [93]:
# TODO A3 — buktikan jawaban nomor 3 dengan kode
# Periksa apakah ada kolom omzet SESUDAH pelatihan di dataset ini.
[col for col in df.columns if 'omzet' in col]
# Petunjuk: cari nama kolom yang memuat kata 'omzet'
# Expected: hanya ada satu kolom omzet, yaitu omzet saat mendaftar

['omzet_usaha_bulanan']

---
## Bagian B — Skala pengukuran

### TODO B1 — klasifikasikan delapan kolom berikut

Isi tabel di sel Markdown ini. Pilihan: **nominal · ordinal · interval · rasio**.

| Kolom | Skala | Alasan singkat |
|---|---|---|
| `kategori_usaha` | Nominal | Berupa kategori dan tidak memiliki urutan |
| `pendidikan_terakhir` | Ordinal | Jenjang pendidikan memiliki urutan |
| `skor_prates` | Rasio | Memiliki nilai  0 dan perbandingan nilai d  apat dilakukan |
| `omzet_usaha_bulanan` | Rasio | Memiliki 0 dan perbandingan nominal bisa dilakukan |
| `jumlah_karyawan` | Rasio | Memiliki 0 yang bermakna |
| `tingkat_kepuasan` | Ordinal | Tingkat kepuasan berurutan tapi jarak antar tingkat belum tentu sama |
| `tanggal_daftar` | Interval | Tidak memiliki nol absolut |
| `kecamatan` | Nominal | Kategori dan tidak memiliki urutan |

In [94]:
# TODO B2 — perbaiki satu kolom ordinal yang salah tipe
# a. Jadikan 'pendidikan_terakhir' bertipe kategori berurutan
#    Urutan: SD < SMP < SMA/SMK < D3 < S1 < S2
urutan = ['SD', 'SMP', 'SMA/SMK', 'D3', 'S1', 'S2']

df['pendidikan_terakhir'] = pd.Categorical(
    df['pendidikan_terakhir'],
    categories=urutan,
    ordered=True
)
# b. Tampilkan value_counts() yang sudah urut menurut jenjang (bukan abjad)
print(df['pendidikan_terakhir'].value_counts().sort_index())
# c. Cetak median jenjang pendidikan lewat .cat.codes
median_kode = df['pendidikan_terakhir'].cat.codes.median()
print(median_kode)
# Expected: median = SMA/SMK

pendidikan_terakhir
SD          24
SMP         71
SMA/SMK    281
D3         107
S1         124
S2          13
Name: count, dtype: int64
2.0

In [95]:
# TODO B3 — ubah dua kolom tanggal menjadi bertipe datetime
# Kolom: tanggal_lahir dan tanggal_daftar
df['tanggal_lahir'] = pd.to_datetime(df['tanggal_lahir'])
df['tanggal_daftar'] = pd.to_datetime(df['tanggal_daftar'])
# Lalu cetak tanggal pendaftaran paling awal dan paling akhir
print("Pendaftaran paling awal:", df['tanggal_daftar'].min())
print("Pendaftaran paling akhir:", df['tanggal_daftar'].max())
# Expected: rentang pendaftaran berada di tahun 2025

Pendaftaran paling awal: 2025-02-01 00:00:00
Pendaftaran paling akhir: 2025-05-31 00:00:00

---
## Bagian C — Kamus data

Kamus data adalah satu baris penjelasan untuk setiap kolom. Bangkitkan kerangkanya dengan kode, isi maknanya sendiri.

In [96]:
# TODO C1 — bangkitkan kerangka kamus data
# Buat DataFrame bernama 'kamus' dengan kolom:
#   nama_kolom, tipe_data, nilai_unik, nilai_kosong, contoh_nilai
df_kamus = pd.DataFrame({
    'nama_kolom': df.columns,
    'tipe_data': df.dtypes.astype(str).values,
    'nilai_unik': [df[col].nunique() for col in df.columns],
    'nilai_kosong': [df[col].isnull().sum() for col in df.columns],
    'contoh_nilai': [df[col].iloc[0] for col in df.columns]
})
# lalu tambahkan empat kolom kosong yang akan diisi manual:
df_kamus['deskripsi'] = ''
df_kamus['skala_pengukuran'] = ''
df_kamus['kategori_data_pribadi'] = ''
df_kamus['tindakan_penanganan'] = ''
print(df_kamus.shape)
df_kamus
# Expected: 28 baris x 9 kolom
#   deskripsi, skala_pengukuran, kategori_data_pribadi, tindakan_penanganan
# Expected: 28 baris x 9 kolom

(28, 9)

,nama_kolom,tipe_data,nilai_unik,nilai_kosong,contoh_nilai,deskripsi,skala_pengukuran,kategori_data_pribadi,tindakan_penanganan
0,id_peserta,object,620,0,PLT-2025-1309,,,,
1,nama_lengkap,object,450,0,Ratna Hidayat,,,,
2,nik_dummy,int64,620,0,99991405899249,,,,
3,no_hp,float64,611,9,80004260813.0,,,,
4,email,object,450,0,ratna.hidayat@contoh.example,,,,
5,alamat_jalan,object,620,0,Jl. Cempaka No. 106 RT 02/RW 10,,,,
6,kelurahan,object,26,0,Sukatani,,,,
7,kecamatan,object,19,0,Tapos,,,,
8,kota,object,1,0,Depok,,,,
9,tanggal_lahir,datetime64[ns],598,0,1989-05-14 00:00:00,,,,
10,jenis_kelamin,object,2,0,P,,,,
11,pendidikan_terakhir,category,6,0,SMP,,,,
12,status_disabilitas,object,2,0,Tidak,,,,
13,jumlah_anak,int64,5,0,3,,,,
14,penghasilan_pribadi_bulanan,int64,110,0,500000,,,,
15,nama_usaha,object,185,0,CV Mandiri Jaya,,,,
16,kategori_usaha,object,5,0,Kuliner,,,,
17,produk_utama,object,19,0,Roti dan kue,,,,
18,lama_usaha_tahun,float64,119,0,12.8,,,,
19,jumlah_karyawan,int64,11,0,4,,,,
20,omzet_usaha_bulanan,int64,293,0,2950000,,,,
21,pernah_ikut_pelatihan,object,2,0,Tidak,,,,
22,kanal_pendaftaran,object,4,0,Datang langsung,,,,
23,tanggal_daftar,datetime64[ns],120,0,2025-04-04 00:00:00,,,,
24,kehadiran_persen,int64,46,0,75,,,,
25,skor_prates,int64,64,0,52,,,,
26,skor_pascates,float64,64,34,67.0,,,,
27,tingkat_kepuasan,float64,28,18,5.0,,,,

In [97]:
# TODO C2 — kolom mana yang punya nilai kosong?
# Tampilkan hanya baris kamus yang nilai_kosong-nya lebih dari 0
df_kamus[df_kamus['nilai_kosong'] > 0]
# Expected: tepat 3 kolom yang punya nilai kosong

,nama_kolom,tipe_data,nilai_unik,nilai_kosong,contoh_nilai,deskripsi,skala_pengukuran,kategori_data_pribadi,tindakan_penanganan
3,no_hp,float64,611,9,80004260813.0,,,,
26,skor_pascates,float64,64,34,67.0,,,,
27,tingkat_kepuasan,float64,28,18,5.0,,,,

### TODO C3 — isi kamus untuk lima kolom

Lengkapi tabel berikut. Deskripsi ditulis sebagai kalimat lengkap, bukan pengulangan nama kolom.

| Kolom | Deskripsi | Skala | Satuan |
|---|---|---|---|
| `lama_usaha_tahun` | Menunjukkan lamanya usaha peserta telah berjalan sejak mulai didirikan. | Rasio | Tahun |
| `kehadiran_persen` | Menunjukkan persentase kehadiran peserta selama mengikuti pelatihan. | Rasio | Persen |
| `skor_pascates` | Menunjukkan nilai yang diperoleh peserta setelah mengikuti pelatihan. | Rasio | Skor |
| `kanal_pendaftaran` | Menunjukkan media atau cara yang digunakan peserta untuk melakukan pendaftaran pelatihan. | Nominal | Nama Media |
| `jumlah_anak` | Menunjukkan jumlah anak yang dimiliki oleh peserta. | Rasio | Angka |

---
## Bagian D — Menandai data pribadi

| Kategori | Artinya |
|---|---|
| **pengenal langsung** | Sendirian sudah menunjuk ke satu orang |
| **quasi-identifier** | Sendirian aman, gabungannya menunjuk ke satu orang |
| **data spesifik** | Bocornya merugikan lebih berat (kesehatan, keuangan pribadi, data anak) |
| **bukan data pribadi** | Tidak menunjuk ke orang; inilah bahan analisis |

In [98]:
# TODO D1 — susun tabel penandaan Anda sendiri
# Buat dictionary bernama PENANDAAN berisi pasangan:
#     'nama_kolom': ('kategori', 'tindakan')
# Tindakan yang tersedia: 'hapus', 'hash', 'generalisasi', 'pertahankan'
# Kolom yang tidak Anda daftarkan dianggap 'bukan data pribadi' + 'pertahankan'.
#
# Lalu bangun DataFrame 'tanda' dengan kolom: nama_kolom, kategori, tindakan
# dan cetak jumlah kolom per kategori.
# Expected: pengenal langsung >= 5 kolom; data spesifik >= 3 kolom
PENANDAAN = {
    'id_peserta': ('pengenal langsung', 'hash'),
    'nama_lengkap': ('pengenal langsung', 'hapus'),
    'nik_dummy': ('pengenal langsung', 'hapus'),
    'no_hp': ('pengenal langsung', 'hapus'),
    'email': ('pengenal langsung', 'hapus'),
    'alamat_jalan': ('pengenal langsung', 'hapus'),

    'tanggal_lahir': ('quasi-identifier', 'generalisasi'),
    'kelurahan': ('quasi-identifier', 'generalisasi'),
    'kecamatan': ('quasi-identifier', 'generalisasi'),
    'kota': ('quasi-identifier', 'generalisasi'),

    'status_disabilitas': ('data spesifik', 'generalisasi'),
    'penghasilan_pribadi_bulanan': ('data spesifik', 'generalisasi'),
    'jumlah_anak': ('data spesifik', 'generalisasi')
}
tanda = pd.DataFrame([
    {'nama_kolom': kolom, 'kategori': kategori, 'tindakan': tindakan}
    for kolom, (kategori, tindakan) in PENANDAAN.items()
])
print(tanda['kategori'].value_counts())
tanda

kategori
pengenal langsung    6
quasi-identifier     4
data spesifik        3
Name: count, dtype: int64

                     nama_kolom           kategori      tindakan
0                    id_peserta  pengenal langsung          hash
1                  nama_lengkap  pengenal langsung         hapus
2                     nik_dummy  pengenal langsung         hapus
3                         no_hp  pengenal langsung         hapus
4                         email  pengenal langsung         hapus
5                  alamat_jalan  pengenal langsung         hapus
6                 tanggal_lahir   quasi-identifier  generalisasi
7                     kelurahan   quasi-identifier  generalisasi
8                     kecamatan   quasi-identifier  generalisasi
9                          kota   quasi-identifier  generalisasi
10           status_disabilitas      data spesifik  generalisasi
11  penghasilan_pribadi_bulanan      data spesifik  generalisasi
12                  jumlah_anak      data spesifik  generalisasi

### TODO D2 — pertanggungjawabkan tiga keputusan

Tiga kolom berikut sering diperdebatkan. Tulis keputusan Anda **beserta alasannya**.

| Kolom | Kategori pilihan Anda | Tindakan | Alasan |
|---|---|---|---|
| `nama_usaha` | quasi-identifier | Generalisasi | Nama usaha dapat digunakan untuk mengarah pada usaha tertentu dan berpotensi membantu mengidentifikasi pemiliknya |
| `omzet_usaha_bulanan` | bukan data pribadi | Pertahankan | Omzet merupakan informasi mengenai kondisi usaha, bukan informasi pribadi yang secara langsung mengidentifikasi peserta |
| `id_peserta` | pengenal langsung | Hash | ID digunakan untuk membedakan satu peserta/baris dengan peserta lainnya, sehingga lebih tepat dipertahankan dalam bentuk tersamarkan |

> Petunjuk untuk `nama_usaha`: bayangkan seseorang mencari nama itu di mesin pencari.
> Petunjuk untuk `omzet_usaha_bulanan`: apakah ini data tentang **orang** atau tentang **usaha**?
> Petunjuk untuk `id_peserta`: apakah Anda masih perlu membedakan satu baris dari baris lain?

---
## Bagian E — Menerapkan tiga tindakan

In [99]:
# TODO E1 — HAPUS
# Buat DataFrame baru bernama 'aman' yang sudah membuang semua kolom bertindakan 'hapus'.
# Cetak berapa kolom yang dibuang dan berapa yang tersisa.
kolom_hapus = tanda.loc[tanda['tindakan'] == 'hapus', 'nama_kolom']

aman = df.drop(columns=kolom_hapus)

print("Kolom yang dibuang:", len(kolom_hapus))
print("Kolom yang tersisa:", aman.shape[1])
kolom_hapus = tanda.loc[
    (tanda['tindakan'] == 'hapus') &
    (tanda['nama_kolom'] != 'id_peserta'),
    'nama_kolom'
]
aman = df.drop(columns=kolom_hapus)

print("Kolom yang dibuang:", len(kolom_hapus))
print("Kolom yang tersisa:", aman.shape[1])

Kolom yang dibuang: 5
Kolom yang tersisa: 23
Kolom yang dibuang: 5
Kolom yang tersisa: 23

In [100]:
# TODO E2 — HASH
# Tulis fungsi samarkan(nilai, garam) yang mengembalikan 12 karakter pertama
# dari sha256(garam + nilai). Kembalikan np.nan bila nilainya kosong.
# Terapkan pada kolom yang Anda beri tindakan 'hash'.
# Expected: nilai asli dan hasil hash berbeda, dan nilai asli yang sama menghasilkan hash yang sama

GARAM = 'capybara'
import hashlib
import numpy as np

def samarkan(nilai, garam):
    if pd.isna(nilai):
        return np.nan

    teks = garam + str(nilai)
    hasil_hash = hashlib.sha256(teks.encode()).hexdigest()

    return hasil_hash[:12]
aman['id_peserta'] = aman['id_peserta'].apply(
    lambda nilai: samarkan(nilai, GARAM)
)
aman['id_peserta'] = aman['id_peserta'].apply(
    lambda nilai: samarkan(nilai, GARAM)
)
aman['id_peserta'].head()

0    754925722eb5
1    28a90a80a5fa
2    80a4798a0e10
3    e4b97325d601
4    04e426499221
Name: id_peserta, dtype: object

In [101]:
# TODO E3 — buktikan hash bersifat konsisten dan tidak terbaca
# a. Hash dua kali nilai yang sama, tunjukkan hasilnya identik
nilai = df['id_peserta'].iloc[0]
hash1 = samarkan(nilai, GARAM)
hash2 = samarkan(nilai, GARAM)
print("Hash 1:", hash1)
print("Hash 2:", hash2)
print("Identik:", hash1 == hash2)
# b. Hash dua nilai berbeda, tunjukkan hasilnya berbeda
nilai1 = df['id_peserta'].iloc[0]
nilai2 = df['id_peserta'].iloc[1]
hash1 = samarkan(nilai1, GARAM)
hash2 = samarkan(nilai2, GARAM)
print("Hash nilai 1:", hash1)
print("Hash nilai 2:", hash2)
print("Berbeda:", hash1 != hash2)

Hash 1: 1055aae82c17
Hash 2: 1055aae82c17
Identik: True
Hash nilai 1: 1055aae82c17
Hash nilai 2: b474dfd8f7f6
Berbeda: True

**Jawaban Anda:** kalau `GARAM` ikut ter-*commit* ke GitHub, apa yang masih terlindungi dan apa yang tidak?

Jika GARAM ikut tercommit ke GitHub, nilai asli yang sudah di-hash tetap tidak langsung terlihat karena hash tidak dapat dibaca kembali menjadi nilai asli. Namun, perlindungan menjadi lebih lemah jika orang lain mengetahui GARAM dan dapat mencoba membuat hash dari nilai yang mereka tebak untuk mencocokkannya. Jadi, GARAM seharusnya tetap dirahasiakan.

In [102]:
# TODO E4 — GENERALISASI
# a. Hitung usia peserta pada tanggal acuan 1 September 2025
ACUAN = pd.Timestamp('2025-09-01')
aman['usia'] = ACUAN.year - df['tanggal_lahir'].dt.year
belum_ulang_tahun = (
    (df['tanggal_lahir'].dt.month > ACUAN.month) |
    (
        (df['tanggal_lahir'].dt.month == ACUAN.month) &
        (df['tanggal_lahir'].dt.day > ACUAN.day)
    )
)
aman.loc[belum_ulang_tahun, 'usia'] -= 1
print(aman['usia'].head())
# b. Buat kolom 'kelompok_umur' dengan batas: <25, 25-34, 35-44, 45-54, 55+
aman['kelompok_umur'] = pd.cut(
    aman['usia'],
    bins=[0, 24, 34, 44, 54, float('inf')],
    labels=['<25', '25-34', '35-44', '45-54', '55+']
)
print(aman['kelompok_umur'].value_counts().sort_index())
# c. Buang kolom tanggal_lahir dan kelurahan dari 'aman'
print('tanggal_lahir' in aman.columns)
print('kelurahan' in aman.columns)
# d. Rapikan kolom kecamatan yang sebagian tertulis KAPITAL
aman['kecamatan'] = aman['kecamatan'].str.strip().str.title()
print("Jumlah kecamatan unik:", aman['kecamatan'].nunique())
# Expected: kelompok terbanyak adalah 35-44; kecamatan punya tepat 10 nilai unik

ACUAN = pd.Timestamp('2025-09-01')

0    36
1    37
2    27
3    41
4    52
Name: usia, dtype: int32
kelompok_umur
<25       53
25-34    153
35-44    267
45-54    108
55+       39
Name: count, dtype: int64
True
True
Jumlah kecamatan unik: 10

---
## Bagian F — Memeriksa sisa risiko

Menghapus nama belum tentu cukup. Untuk setiap kombinasi quasi-identifier, hitung berapa orang yang punya kombinasi sama. Nilai terkecil disebut **k**. Target kelas ini: **k ≥ 5**.

In [103]:
# TODO F1 — tulis fungsi cek_k(data, kolom)
# Kembalikan Series berisi: k (grup terkecil), grup berisi 1 orang, total grup
def cek_k(data, kolom):
    grup = data.groupby(kolom).size()
    k = grup.min()
    grup_1_orang = grup[grup == 1]
    total_grup = len(grup)
    return k, grup_1_orang, total_grup

In [104]:
# TODO F2 — ukur risiko SEBELUM penanganan
# Gunakan data asli df dengan kolom:
#   ['kelurahan', 'jenis_kelamin', 'pendidikan_terakhir', 'tanggal_lahir']
# Expected: k = 1 dan SELURUH 620 baris berada di grup berisi satu orang
df_f2 = df.copy()
df_f2['pendidikan_terakhir'] = df_f2['pendidikan_terakhir'].astype(str)
hasil_sebelum = cek_k(
    df_f2,
    ['kelurahan', 'jenis_kelamin', 'pendidikan_terakhir', 'tanggal_lahir']
)
print(hasil_sebelum[0])
print(len(hasil_sebelum[1]))
print(hasil_sebelum[2])

1
620
620

**Jawaban Anda:** keempat kolom itu tidak memuat nama maupun nomor telepon. Jelaskan dalam dua kalimat mengapa hasilnya tetap berbahaya.

_Meskipun tidak memuat nama atau nomor telepon, kombinasi kelurahan, jenis kelamin, pendidikan terakhir, dan tanggal lahir dapat menjadi petunjuk yang cukup untuk membedakan seseorang dari peserta lain. Hasil k = 1 menunjukkan bahwa setiap peserta memiliki kombinasi yang unik, sehingga seseorang yang memiliki informasi tersebut berpotensi mengenali peserta tertentu._

In [105]:
# TODO F3 — ukur risiko SESUDAH generalisasi
# Gunakan 'aman' dengan kolom:
#   ['kecamatan', 'jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']
# Expected: jumlah grup berisi satu orang turun banyak, tetapi k masih 1
aman_f3 = aman.copy()
aman_f3['pendidikan_terakhir'] = aman_f3['pendidikan_terakhir'].astype(str)
aman_f3['kelompok_umur'] = aman_f3['kelompok_umur'].astype(str)
hasil_sesudah = cek_k(
    aman_f3,
    ['kecamatan', 'jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']
)
print("k =", hasil_sesudah[0])
print("Grup berisi 1 orang =", len(hasil_sesudah[1]))
print("Total grup =", hasil_sudah[2] if False else hasil_sesudah[2])

k = 1
Grup berisi 1 orang = 138
Total grup = 266

In [106]:
# TODO F4 — TANTANGAN: capai k >= 5
# Generalisasikan lebih jauh sampai k >= 5, dengan MEMPERTAHANKAN sebanyak mungkin informasi.
# Anda boleh: memperlebar kelompok umur, menggabungkan kecamatan kecil menjadi 'Lainnya',
# atau mengeluarkan satu kolom dari daftar quasi-identifier.
# Catat setiap pilihan dan dampaknya terhadap k.
# Petunjuk: ada lebih dari satu jawaban benar. Yang dinilai adalah alasannya.
aman_f4 = aman.copy()
aman_f4['kelompok_umur'] = pd.cut(
    aman_f4['usia'],
    bins=[0, 29, 39, 49, float('inf')],
    labels=['<30', '30-39', '40-49', '50+']
)
aman_f4['pendidikan_terakhir'] = aman_f4['pendidikan_terakhir'].astype(str)
aman_f4['kelompok_umur'] = aman_f4['kelompok_umur'].astype(str)
hasil_f4 = cek_k(
    aman_f4,
    ['kecamatan', 'jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']
)
print("k =", hasil_f4[0])
print("Grup berisi 1 orang =", len(hasil_f4[1]))
print("Total grup =", hasil_f4[2])
hasil_f4_2 = cek_k(
    aman_f4,
    ['kecamatan', 'pendidikan_terakhir', 'kelompok_umur']
)
print("k =", hasil_f4_2[0])
print("Grup berisi 1 orang =", len(hasil_f4_2[1]))
print("Total grup =", hasil_f4_2[2])
print(aman_f4['kecamatan'].value_counts())
hasil_f4_3 = cek_k(
    aman_f4,
    ['pendidikan_terakhir', 'kelompok_umur']
)
print("k =", hasil_f4_3[0])
print("Grup berisi 1 orang =", len(hasil_f4_3[1]))
print("Total grup =", hasil_f4_3[2])
aman_f4_2 = aman_f4.copy()
aman_f4_2['kelompok_pendidikan'] = aman_f4_2['pendidikan_terakhir'].replace({
    'SD': 'SD/SMP',
    'SMP': 'SD/SMP',
    'SMA/SMK': 'SMA/SMK',
    'D3': 'D3/S1/S2',
    'S1': 'D3/S1/S2',
    'S2': 'D3/S1/S2'
})
hasil_f4_4 = cek_k(
    aman_f4_2,
    ['kelompok_pendidikan', 'kelompok_umur']
)
print("k =", hasil_f4_4[0])
print("Grup berisi 1 orang =", len(hasil_f4_4[1]))
print("Total grup =", hasil_f4_4[2])

k = 1
Grup berisi 1 orang = 112
Total grup = 252
k = 1
Grup berisi 1 orang = 47
Total grup = 162
kecamatan
Pancoran Mas    99
Sukmajaya       95
Cimanggis       90
Beji            87
Cinere          67
Tapos           49
Limo            43
Bojongsari      41
Cipayung        26
Sawangan        23
Name: count, dtype: int64
k = 2
Grup berisi 1 orang = 0
Total grup = 24
k = 10
Grup berisi 1 orang = 0
Total grup = 12

**Jawaban Anda:** tulis kombinasi yang Anda pilih, nilai k yang dicapai, dan informasi apa yang Anda korbankan untuk mencapainya.

_**Jawaban Anda:**

Kombinasi yang dipilih adalah kelompok pendidikan dan kelompok umur. Kelompok pendidikan digeneralisasi menjadi SD/SMP, SMA/SMK, dan D3/S1/S2, sedangkan kelompok umur diperlebar menjadi <30, 30–39, 40–49, dan 50+. Dengan kombinasi tersebut diperoleh nilai k = 10, sehingga sudah memenuhi target k ≥ 5. Informasi yang dikorbankan adalah detail pendidikan dan kelompok umur menjadi lebih umum, serta informasi jenis kelamin dan kecamatan tidak lagi digunakan dalam kombinasi quasi-identifier. Namun, data asli tetap dipertahankan dalam dataset.
)_

In [107]:
# TODO F5 — sel kecil pada tabel agregat
# a. Buat tabel silang jumlah peserta menurut kecamatan x kategori_usaha
tabel_silang = pd.crosstab(
    aman['kecamatan'],
    aman['kategori_usaha']
)
print(tabel_silang)
# b. Hitung berapa sel yang terisi tetapi berisi kurang dari 5 peserta
jumlah_sel_kecil = ((tabel_silang >= 1) & (tabel_silang < 5)).sum().sum()
print("Jumlah sel berisi 1-4 peserta:", jumlah_sel_kecil)
# Expected: ada sel bernilai 1-4; sel seperti ini tidak boleh ditampilkan apa adanya di laporan

kategori_usaha  Fesyen  Jasa Digital  Kriya  Kuliner  Pertanian
kecamatan
Beji                14            10     15       42          6
Bojongsari           7             5      4       23          2
Cimanggis           16             8     15       44          7
Cinere              16            11      8       23          9
Cipayung             4             6      5       10          1
Limo                10             4     10       15          4
Pancoran Mas        25            12     19       31         12
Sawangan             5             3      3       10          2
Sukmajaya           22            14     11       36         12
Tapos               11             5     11       16          6
Jumlah sel berisi 1-4 peserta: 9

---
## Bagian G — Diterapkan pada proyek tim (dikerjakan di luar kelas)

Bagian ini adalah isi **M1**. Kerjakan bersama tim pada dataset proyek Anda sendiri.

### G1 — Pertanyaan analisis
Tulis **3–5 pertanyaan** yang lolos tiga uji. Untuk setiap pertanyaan, sebutkan kolom yang akan dipakai.

1. Apa perbedaan karakteristik orang yang memiliki label diabetes dan yang tidak?
2. Apakah BMI orang dengan label diabetes berbeda dari orang tanpa label diabetes?	(bmi, diabetes)
3. Pada kelompok usia berapa label diabetes lebih banyak ditemukan?	(age, diabetes)

### G2 — Provenans data
Catat lima butir berikut di README repositori tim:

| Butir | Isi |
|---|---|
| Nama sumber | Mohammed Mustafa |
| Tautan atau nama instansi | https://www.kaggle.com/datasets/iammustafatz/diabetes-prediction-dataset |
| Tanggal pengambilan | 28 September 2026 |
| Lisensi atau nomor surat izin | Data Files Original Authors |
| Kalimat sitasi untuk laporan | [1] M. Mustofa, “Diabetes Prediction Dataset,” *Kaggle*. [Online]. Available: https://www.kaggle.com/datasets/iammustafatz/diabetes-prediction-dataset. [Accessed: Oct. 11, 2026]. |

### G3 — Kamus data
Isi `TEMPLATE_Kamus_Data.csv` untuk **setiap** kolom dataset tim, termasuk kolom `kategori_data_pribadi` dan `tindakan_penanganan`. Simpan sebagai `data_dictionary.md` atau `.csv` di repositori.

In [108]:
# G4 — jalankan penanganan pada data tim dan periksa nilai k
# Salin pola Bagian E dan F, ganti dataset dan nama kolomnya.
# Simpan hasilnya ke data/processed/ dan JANGAN unggah data/raw/
import pandas as pd
df = pd.read_csv("/content/diabetes_prediction_dataset.csv")
print("Ukuran dataset:", df.shape)
display(df.head())

Ukuran dataset: (100000, 9)

   gender   age  hypertension  heart_disease smoking_history    bmi  HbA1c_level  blood_glucose_level  diabetes
0  Female  80.0             0              1           never  25.19          6.6                  140         0
1  Female  54.0             0              0         No Info  27.32          6.6                   80         0
2    Male  28.0             0              0           never  27.32          5.7                  158         0
3  Female  36.0             0              0         current  23.45          5.0                  155         0
4    Male  76.0             1              1         current  20.14          4.8                  155         0

In [109]:
# G4.1 — Menentukan tindakan penanganan data

tanda = pd.DataFrame({
    'nama_kolom': df.columns,
    'tindakan': [
        'pertahankan',  # gender
        'generalisasi', # age
        'pertahankan',  # hypertension
        'pertahankan',  # heart_disease
        'pertahankan',  # smoking_history
        'pertahankan',  # bmi
        'pertahankan',  # HbA1c_level
        'pertahankan',  # blood_glucose_level
        'pertahankan'   # diabetes
    ]
})

display(tanda)

            nama_kolom      tindakan
0               gender   pertahankan
1                  age  generalisasi
2         hypertension   pertahankan
3        heart_disease   pertahankan
4      smoking_history   pertahankan
5                  bmi   pertahankan
6          HbA1c_level   pertahankan
7  blood_glucose_level   pertahankan
8             diabetes   pertahankan

In [110]:
# G4.2 — Membuat DataFrame hasil penanganan

kolom_hapus = tanda.loc[
    tanda['tindakan'] == 'hapus',
    'nama_kolom'
]

aman = df.drop(columns=kolom_hapus).copy()

print("Kolom yang dibuang:", len(kolom_hapus))
print("Kolom yang tersisa:", aman.shape[1])

# Generalisasi usia
aman['kelompok_umur'] = pd.cut(
    aman['age'],
    bins=[-1, 24, 34, 44, 54, float('inf')],
    labels=['<25', '25-34', '35-44', '45-54', '55+'],
    include_lowest=True
)

print("\nDistribusi kelompok umur:")
print(aman['kelompok_umur'].value_counts().sort_index())

Kolom yang dibuang: 0
Kolom yang tersisa: 9

Distribusi kelompok umur:
kelompok_umur
<25      25885
25-34    12875
35-44    13648
45-54    15330
55+      32262
Name: count, dtype: int64

In [111]:
# G4.3 — Fungsi pemeriksaan k

def cek_k(data, kolom):
    grup = data.groupby(kolom, observed=True).size()
    k = grup.min()
    grup_1_orang = grup[grup == 1]
    total_grup = len(grup)

    return k, grup_1_orang, total_grup

# Sebelum generalisasi
hasil_sebelum = cek_k(
    df,
    ['gender', 'age', 'smoking_history']
)

print("SEBELUM GENERALISASI")
print("k =", hasil_sebelum[0])
print("Grup berisi 1 orang =", len(hasil_sebelum[1]))
print("Total grup =", hasil_sebelum[2])

# Sesudah generalisasi
hasil_sesudah = cek_k(
    aman,
    ['gender', 'kelompok_umur', 'smoking_history']
)

print("\nSESUDAH GENERALISASI")
print("k =", hasil_sesudah[0])
print("Grup berisi 1 orang =", len(hasil_sesudah[1]))
print("Total grup =", hasil_sesudah[2])
print(aman['kelompok_umur'].value_counts().sort_index())

SEBELUM GENERALISASI
k = 1
Grup berisi 1 orang = 54
Total grup = 1014

SESUDAH GENERALISASI
k = 1
Grup berisi 1 orang = 6
Total grup = 69
kelompok_umur
<25      25885
25-34    12875
35-44    13648
45-54    15330
55+      32262
Name: count, dtype: int64

In [112]:
import os

os.makedirs('data/processed', exist_ok=True)

aman.to_csv(
    'data/processed/diabetes_aman.csv',
    index=False
)

print("Hasil tersimpan di data/processed/diabetes_aman.csv")

Hasil tersimpan di data/processed/diabetes_aman.csv

In [113]:
grup_satu_orang = hasil_sesudah[1]

display(grup_satu_orang)

gender  kelompok_umur  smoking_history
Other   25-34          ever               1
                       not current        1
        35-44          not current        1
        45-54          No Info            1
                       not current        1
        55+            No Info            1
dtype: int64

In [114]:
#G4.4 mencoba meningkatkan nilai k hingga (k=> 5)
#Gabungkan kategori usia
aman['kelompok_umur_baru'] = pd.cut(
    aman['age'],
    bins=[-1, 34, 54, float('inf')],
    labels=['<35', '35-54', '55+'],
    include_lowest=True
)
print(aman['kelompok_umur_baru'].value_counts().sort_index())
#Hitung ulang nilai k
hasil_lebih_luas = cek_k(
    aman,
    ['gender', 'kelompok_umur_baru', 'smoking_history']
)

print("SESUDAH GENERALISASI LEBIH LUAS")
print("k =", hasil_lebih_luas[0])
print("Grup berisi 1 orang =", len(hasil_lebih_luas[1]))
print("Total grup =", hasil_lebih_luas[2])
#Periksa 3 grup tunggal
hasil_lebih_luas[1].reset_index(name='jumlah')
#Periksa jumlah tiap kategori merokok
aman['smoking_history'].value_counts(dropna=False)
#Generalisasi riwayat merokok
aman['riwayat_merokok_baru'] = aman['smoking_history'].replace({
    'ever': 'Riwayat merokok lainnya',
    'former': 'Riwayat merokok lainnya',
    'current': 'Riwayat merokok lainnya',
    'not current': 'Riwayat merokok lainnya'
})
print(aman['riwayat_merokok_baru'].value_counts(dropna=False))
#Hitung k kembali
hasil_merokok = cek_k(
    aman,
    ['gender', 'kelompok_umur_baru', 'riwayat_merokok_baru']
)
print("SESUDAH GENERALISASI RIWAYAT MEROKOK")
print("k =", hasil_merokok[0])
print("Grup berisi 1 orang =", len(hasil_merokok[1]))
print("Total grup =", hasil_merokok[2])
hasil_merokok[1].reset_index(name='jumlah')
aman['gender'].value_counts(dropna=False)
hasil_tanpa_gender = cek_k(
    aman,
    ['kelompok_umur_baru', 'riwayat_merokok_baru']
)

# Menampilkan hasil evaluasi nilai k
print("HASIL PENGUJIAN TANPA GENDER")
print("Nilai k:", hasil_tanpa_gender[0])
print("Jumlah grup berisi 1 orang:", len(hasil_tanpa_gender[1]))
print("Jumlah seluruh grup:", hasil_tanpa_gender[2])

kelompok_umur_baru
<35      38760
35-54    28978
55+      32262
Name: count, dtype: int64
SESUDAH GENERALISASI LEBIH LUAS
k = 1
Grup berisi 1 orang = 3
Total grup = 43
riwayat_merokok_baru
No Info                    35816
never                      35095
Riwayat merokok lainnya    29089
Name: count, dtype: int64
SESUDAH GENERALISASI RIWAYAT MEROKOK
k = 1
Grup berisi 1 orang = 2
Total grup = 24
HASIL PENGUJIAN TANPA GENDER
Nilai k: 6964
Jumlah grup berisi 1 orang: 0
Jumlah seluruh grup: 9

### G5 — Daftar periksa sebelum `git push`

- [ ] `data/raw/` masuk `.gitignore`
- [ ] Tidak ada nama, NIK, nomor telepon, surel, atau alamat di berkas mana pun
- [ ] Keluaran sel yang sempat menampilkan data pribadi sudah dibersihkan
- [ ] Garam hash tidak tertulis di dalam notebook
- [ ] Kamus data memuat kategori dan tindakan untuk setiap kolom
- [ ] Nilai k pada data yang diunggah sudah dihitung dan dicatat
- [ ] Bila masih ragu: repositori dibuat **privat**

> Menghapus berkas lalu *commit* ulang **tidak** menghilangkan data dari riwayat Git. > Periksa **sebelum** *commit* pertama.